# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml

---

- name: custom facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: opnsense facts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ansible/facts.d/{{ item }}"
    mode: 0755
  with_items:
    - opnsense.fact
  register: opnf

- name: reload ansible_local facts
  ansible.builtin.setup:
    filter: ansible_local  # noqa no-handler
  when: opnf.changed

...
